[package]
name = "v14-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
desub-current = { path = "../../desub-current" }
anyhow = "1.0.44"
hex = "0.4.3"
pretty_env_logger = "0.4.0"
