[workspace]
members = [
	"bin/tx-decoder",
	"bin/v14-test",
	"core",
	"core_v14",
	"extras",
	"integration_tests",
	"substrate-metadata-versions/metadatav8",
	"substrate-metadata-versions/metadatav9",
	"substrate-metadata-versions/metadatav10",
	"substrate-metadata-versions/metadatav11",
]

#exclude = [
#	"bin/tx-decoder"
#]

[patch.crates-io]
# codec = { git = "https://github.com/insipx/parity-scale-codec", version = "1.3", branch = "insipx/debugging", package = "parity-scale-codec" }
# parity-scale-codec-derive = { path = "derive", version = "^1", git = "https://github.com/insipx/parity-scale-codec", branch="insipx/debugging" }



