[workspace]
members = [
	"bin/tx-decoder",
	"bin/v14-test",
	"core",
	"core_v14",
	"extras",
	"integration_tests",
	"substrate-metadata-versions/metadatav8",
	"substrate-metadata-versions/metadatav9",
	"substrate-metadata-versions/metadatav10",
	"substrate-metadata-versions/metadatav11",
]
