[package]
name = "desub-json-resolver"
version = "0.0.1"
authors = [ "Andrew Plaza <andrew.plaza@parity.io>" ]
edition = "2021"
repository = "https://github.com/paritytech/desub"


[dependencies]
thiserror = "1.0.30"
desub-legacy = { path = "../desub-legacy" }
codec = { version = "2", features = ["derive"], package = "parity-scale-codec" }
log = { version = "0.4" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
syn = { version = "1", features = ["parsing", "derive"] }
phf = { version = "0.10.0", features = [ "macros" ] }

[features]
default = ["default_definitions"]
polkadot = []
default_definitions = []
