[package]
name = "desub-legacy"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/desub/"
description = "Decode Substrate with Backwards-Compatible Metadata"
readme = "README.md"
edition = "2021"

[dependencies]
log = "0.4"
thiserror = "1.0.30"
codec = { version = "2", package = "parity-scale-codec", features = ["bit-vec"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
onig = { version = "5.0", default-features = false }
derive_more = "0.99.3"
dyn-clone = "1.0"
hex = "0.4"
bitvec = { version = "0.20.2", features = ["serde", "alloc"] }
frame-metadata = { version = "14.2", features = ["legacy"] }

desub-common = { path = "../desub-common/" }

sp-core = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-12" }
sp-runtime = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-12" }
pallet-democracy = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-12" }

[dev-dependencies]
runtime-version = { package = "sp-version", git = "https://github.com/paritytech/substrate", tag = "monthly-2021-12" }
pretty_env_logger = "0.4"
hex = "0.4"
